name: Veracode Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  
jobs:
  Veracode-SCA-Agent-Action:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.0b1-buster
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: pip install
        run: |
          python -m pip install --no-cache-dir pip==22.0.4
      
      - name: Listing
        run: |
          ls -lah
      
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |         
          export EXTRA_ARGS='--update-advisor --uri-as-name'
          curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan $EXTRA_ARGS

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'veracode.zip'
        exclusions: '*.git* /*node_modules/* .editorconfig'
    - name: Publicando Artefato
      uses: actions/upload-artifact@v2
      with:
        name: pacoteVeracode
        path: veracode.zip


  pipeline_scan:
    needs: [ build, Veracode-SCA-Agent-Action ]
    runs-on: ubuntu-latest
    name: Pipeline Scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: pacoteVeracode

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          VID: ${{ secrets.VID }}
          VKEY: ${{ secrets.VKEY }}
          file: "veracode.zip"
 

        # variaveis ambientes (vid / vkey / token)
        # SCA
        # actions do zip
        # policy scan
        # pipeline scan
        # sandbox antes do policy
        # policy com quebra

        