name: Veracode Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:

   veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository with Veracode SCA

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        uses: veracode/veracode-sca@v2.1.9


Pipeline_scan:
    needs: build
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: chackout repo
        uses: actions/chackout@v3

      - name: get archive
        uses: actions/download-artifact@v3
        with:
          name: verademo.war

      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          VID: ${{ secrets.VID }}
          VKEY: ${{ secrets.VKEY }}
          file: "verademo.war" 

        # variaveis ambientes (vid / vkey / token)
        # SCA
        # actions do zip
        # policy scan
        # pipeline scan
        # sandbox antes do policy
        # policy com quebra

        